name       : python-distutils-extra
version    : 2.38
release    : 2
source     :
    - https://launchpad.net/python-distutils-extra/trunk/2.38/+download/python-distutils-extra-2.38.tar.gz : 3d100d5d3492f40b3e7a6a4500f71290bfa91e2c50dc31ba8e3ff9b5d82ca153
license    : GPL-2.0
summary    : Python Distutils Extras
description: |
    Easily integrate gettext support, themed icons and scrollkeeper based documentation into Python's distutils
builddeps  :
    - python-setuptools
    - intltool
rundeps    :
    - python-setuptools
    - intltool
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
