name       : python-distutils-extra
version    : 2.39
release    : 4
source     :
    - https://launchpad.net/python-distutils-extra/trunk/2.39/+download/python-distutils-extra-2.39.tar.gz : 723f24f4d65fc8d99b33a002fbbb3771d4cc9d664c97085bf37f3997ae8063af
license    : GPL-2.0
component  : programming.python
summary    : Python Distutils Extras
description: |
    Easily integrate gettext support, themed icons and scrollkeeper based documentation into Python's distutils
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
    - intltool
rundeps    :
    - python-setuptools
    - intltool
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
